  name: Daily Lighthouse Report

on:
  schedule:
    - cron: '0 8 * * *'  # Exécute tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse https://www.cineville.nl --quiet --chrome-flags="--headless" --output=json --output-path=report.json


      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Lighthouse-Report
          path: report.json
